### PR TITLE
sort queried snapshots by date 

### PR DESCRIPTION
**Pull request by kumarpit**
GET requests to `api/snapshots` now returns snapshot entries sorted by date (most recent to least recent)
Tested locally using insomnia

Note: The ticket mentioned that the date string format being followed is `YYYY-MM-DD`. This format allows the `getAllSnapshots` function to simply sort the date strings in lexicographically descending order to get the desired result. If we decide to use some other format, the implementation in this PR wouldn't work.

Update: Implemented date validation on snapshot creation.
- Date format `YYYY-MM-DD`
- Accepted date range `2000-01-01` to `2099-12-31`
- `YYYY-MM-DD` must be separated by `[-]`, example: "2022-01-12" is valid but "2022/01/12" is not
-  Dates must be valid, example: 2022-02-31, 2022-04-31 are not valid dates

Installed the `date-fns` library to help perform date validation.

### CODE REVIEW

**Review by ElisaHu1 — APPROVED** [review]
No problem with me! Approved!

**Comment by kumarpit** [comment]
Thank you! Though I think we should validate the date string, either on the backend or frontend.

**Comment by ElisaHu1** [comment]
I think so, the date should be checked when users are creating the snapshot. which side do you think we should implement the check?

**Comment by kumarpit** [comment]
I agree, checking the date string when creating snapshots seems like the best option to me. Should I add this in this PR?

**Comment by ElisaHu1** [comment]
That would be perfect!

**Comment by kumarpit** [comment]
The accepted range of dates I decided on is `2000-01-01` to `2099-12-31` - is that sufficient for our purposes?
Another question I had was whether we should allow creation of snapshots in the future - i.e dates greater than the date at time of snapshot creation?

**Comment by ElisaHu1** [comment]
I think it is sufficient. I realize that we have date as a required field in snapshot schema, so can we declare date, not as a type of string but as a type of Date?
Or can we get the date on the time the user calls create snapshot from an external API, so we do not need to manually input the date field?

**Comment by ElisaHu1** [comment]
That is a great question, probably without API is easier for you, and flexible for the past snapshot

**Comment by kumarpit** [comment]
I changed the snapshot schema to store date as Date instead of string - now the user still sends strings formatted as `YYYY-MM-DD` and mongoose handles the conversion to js Date object.

**Pull request merged**
