### PR TITLE
snapshot update endpoint

### PR DESCRIPTION
**Pull request by kumarpit**
Implemented snapshot update endpoint, tested locally using Insomnia.

Update: Contributors can now be updated by sending an array of usernames (not 'first name + last name', rather the username field stored in the user document - this results in faster queries since the user collection is indexed on usernames). Also note that usernames are case-insensitive, so sending 'RobErt' and 'robert' produces the same results. 
If a user that doesn't exist is sent in the contributors array, a descriptive error is thrown.

### CODE REVIEW

**Comment by ElisaHu1** [comment]
it seems like I am not able to update the contributor field in a snapshot?
image
In the snapshot.model we have contributors: [{ type: mongoose.ObjectId, ref: "User" }], so it should be able to add auth user or member in?
Thanks!

**Comment by kumarpit** [comment]
So we should be able to send an array of user 'names' and be able to update snapshots?
I initially thought we send in an array of user objectIDs in the request, which is how I tested it.

Screenshot (89)

In this case, I'll add a query on the users collection by name in the `updateSnapshots` function to get their ids, which I'll use to update the snapshot instead of `req.body.contributors`

**Comment by kumarpit** [comment]
I made the changes suggested above, though I have one question, even though now we can send usernames to update the contributors for snapshots, we still store objectIDs for the contributors in the database. Should I update this to store usernames instead?

**Comment by ElisaHu1** [comment]
@KevinetPeng What do you think, I am not very familiar with the initial design of storing objectID, is there a specific reason?
@kumarpit I am assuming that if we store username instead, we should not allow duplicate username?

**Comment by kumarpit** [comment]
yes, usernames are unique so duplication of usernames shouldn't be a problem

**Comment by KevinetPeng** [comment]
usernames should be unique, so I think they can work fine as a UUID. We've already made usernames unique in our user model

**Comment by ElisaHu1** [comment]
The change looks good! now I can change the contributor as well. One minor issue I found is after I input the username, the new snapshot give me the Object id rather than the name itself, I wonder is this by design? 
image

**Comment by kumarpit** [comment]
Currently, yes this is by design. I wasn't sure if we should store usernames - though based on Kevin's comment, I think we can and I'll make that change.

**Comment by ElisaHu1** [comment]
We probably want to update the snapshot schema to reflect this change, because I do not think it is clear to store the storage id rather than the name.

**Comment by kumarpit** [comment]
Yep, I'll make the change now.

**Review by ElisaHu1 — APPROVED** [review]

**Pull request merged**
