### PR TITLE
Changed api/snapshots endpoint to use query params

### PR DESCRIPTION
**Pull request by danielcrookall**
Updated api/snapshots to filter timeline objects based off of specified query parameters: project, categories, date, author.
Date matched based on exact match of the date field. 

Tested with Postman.

### CODE REVIEW

**Comment by ElisaHu1** [comment]
Hello Daniel, thanks you for the update, few questions I have 
1. can you provide an example query we can pass in get all snapshots to filter some snapshot? 
image I tried a bit but does not work. 
2. you mentioned in the comments 'request query parameters (optional): project, categories, date, author', but can I filter with other information like id, tags, title etc?
3. I found you change a lot of the indentation for other methods as well. Is there a particular reason to do so? (Because Arpit is also working on this file and that may cause merge conflict)
Thanks!

**Comment by danielcrookall** [comment]
> Hello Daniel, thanks you for the update, few questions I have
> 
> 1. can you provide an example query we can pass in get all snapshots to filter some snapshot?
>    image I tried a bit but does not work.
> 2. you mentioned in the comments 'request query parameters (optional): project, categories, date, author', but can I filter with other information like id, tags, title etc?
> 3. I found you change a lot of the indentation for other methods as well. Is there a particular reason to do so? (Because Arpit is also working on this file and that may cause merge conflict)
>    Thanks!

Hi Elisa,

1. The query you posted gets back all the snapshots. I thought that if no query params are specified, we simply return all the snapshots from MongoDb. If query params are specified, we return the filtered results. In the picture you sent, the get request to http://localhost:4000/api/snapshots returns all the snapshots in the database. Did I misinterpret this? 

2. This is a good point.  I guess the simple fix for this is just to select the specific fields from the request params, then pass that filter into the query, as opposed to passing the user input directly into the query. 

3. To format the code, I simply used the auto formatter in the IDE I was using. I guess this is an issue if everyone isn't using the same IDE. Not really sure what the best approach to this would be apart from enforcing some formatting style with ESLint. 

Thanks!

**Comment by ElisaHu1** [comment]
Thanks for the fast reply! I read the doc from https://masteringjs.io/tutorials/mongoose/find and could you give me some examples for how to filter out the exact info or time (the one I showed in the screenshot should filter out all the days? )

for the indenting, which IDE are you using?

**Comment by danielcrookall** [comment]
Sure. I'm not 100% familiar with Insomnia, but based off the picture you sent, it doesn't look like the date you entered is being specified as query params in the URL. 

1. No filters (no query params specified). All snapshots retrieved. 
image
{
    "message": "Successfully retrieved all timeline snapshots",
    "data": [
        {
            "categories": [],
            "contributors": [
                "6286fb6b59c7a32b50803f76",
                "61eb548e96aeb81cf897b5ce"
            ],
            "_id": "6064076dd3b059682153bceb",
            "tags": [
                "wow",
                "sick",
                "amazing"
            ],
            "title": "Test 1",
            "description": "this is a test!",
            "imageURL": "asdf",
            "date": "2021/03/30",
            "createdAt": "2021-03-31T05:23:57.126Z",
            "updatedAt": "2022-05-23T21:50:35.323Z",
            "__v": 0
        },
        {
            "categories": [],
            "contributors": [
                "kevin peng",
                "shoutout to my mom"
            ],
            "_id": "60dbddbfda3e0b5e7895c23c",
            "tags": [
                "wow",
                "sick",
                "amazing"
            ],
            "title": "Test 1",
            "description": "this is a test! add a test",
            "imageURL": "asdf.jpg",
            "date": "2021/05/19",
            "createdAt": "2021-06-30T02:58:07.285Z",
            "updatedAt": "2022-05-20T02:30:22.703Z",
            "__v": 0
        },
        {
            "categories": [],
            "contributors": [
                "kevin peng",
                "shoutout to my mom"
            ],
            "_id": "60dd0e84824df41d5c7c56a5",
            "tags": [
                "wow",
                "sick",
                "amazing"
            ],
            "title": "Test 3",
            "description": "this is a test!",
            "imageURL": "asdf",
            "date": "2021/03/30",
            "createdAt": "2021-07-01T00:38:28.277Z",
            "updatedAt": "2021-07-01T00:38:28.277Z",
            "__v": 0
        },
        {
            "categories": [
                "test",
                ""
            ],
            "contributors": [
                "62873867dd4b097cc5df6e99"
            ],
            "_id": "6287371add4b097cc5df6e97",
            "title": "Test",
            "description": "asdlkaldksl",
            "imageURL": "apple",
            "date": "2022/05/19",
            "project": "project1",
            "author": "628737ccdd4b097cc5df6e98"
        }
    ]
}

2. Only filtering on a specific date input.

image
3. Filtering on a specific project: 
image

4. Filtering on a specific author:
image

5. Filtering on a specific category: 
image

6. Filtering on a specific date and category:

image


7. Filtering on date, project, categories and author, when the category doesn't exist in the database:
image
8. Filtering on all values: date, project, categories and author: 

image


As for the code editor, I am using IntelliJ IDEA Ultimate.

**Comment by ElisaHu1** [comment]
Thank you so much for the detailed explanation! I have tested most of the features and besides the project, categories, date, author, all other filters also work.
I will approve this request

**Review by ElisaHu1 — APPROVED** [review]

**Pull request closed without merging**
