### PR TITLE
Eason/docker trial

### PR DESCRIPTION
**Pull request by WYC401**
## Description

This is to deploy backend on ec2 and change it to https.

### Changes

* add docker file to deploy in the ec2 
* add pem files for https request
### Updates

Now it can be reviewed

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Assigned PR to all authors
- [ ] Requested at least one reviewer

### CODE REVIEW

**Comment by ElisaHu1** [comment]
are we eventually gonna merge this in?

**Comment by WYC401** [comment]
> are we eventually gonna merge this in?

Yes we should! we should merge it ASAP so  that I can test on my CI/CD

**Comment by ElisaHu1** [comment]
then how are we suppose to test it?

**Comment by ryanyae** [comment]
> then how are we suppose to test it?

A way that we could test it would be if someone were to upload a docker image onto to docker hub and we just use a docker lab to run that docker image

**Review by ElisaHu1 — APPROVED** [review]

**Pull request merged**
