### PR TITLE
Fixed - Backend Exposed Publicly

### PR DESCRIPTION
**Pull request by yasmeen45**
## Description

Backend was exposed publicly (ex. https://vclcontentplatfromserver.com:5000/api/projects). Now added API key required to make requests. Only the frontend can now get information. Requests from the backend and the console in the frontend no longer work, so the backend is protected.

### Changes

Added checks for permissions for all requests on all controllers, and tested them. Also added checks for the API key for all requests. 

The API key is stored in the backend .env file, and the frontend has the hashed key. In the backend, the key is hashed then compared.

### Add API key

In .env file, add: `FRONTEND_API_KEY=w2pCcwb9`

### Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [x] Ran `npm run lint:fix` to format code
- [ ] Assigned PR to all authors
- [x] Requested at least one reviewer

### CODE REVIEW

**Comment by ryanyae** [comment]
@yasmeen45 I was wondering how you went about testing your newly implemented feature?

**Comment by yasmeen45** [comment]
> @yasmeen45 I was wondering how you went about testing your newly implemented feature?

I created tests for the additions onto the existing unit tests. Everything passed with the expected outputs.

I wanted to also run the branch locally and test the commands myself, but I couldn't figure out how to. Can it be done locally?

**Comment by ryanyae** [comment]
> > @yasmeen45 I was wondering how you went about testing your newly implemented feature?
> 
> I created tests for the additions onto the existing unit tests. Everything passed with the expected outputs.
> 
> I wanted to also run the branch locally and test the commands myself, but I couldn't figure out how to. Can it be done locally?

What you would have to do is go to the frontend and see if everything works there. But My only concern is the logic behind your implementation. I see that you made it so that all functions need a header property called 'authorization', but I wonder if credentials will always be neccessary?

**Comment by yasmeen45** [comment]
@ryanyae This is the backend security PR.

**Comment by ryanyae** [comment]
@ax920 @ElisaHu1

**Review by ElisaHu1 — APPROVED** [review]
amazing work!

**Review by ax920 — APPROVED** [review]

**Pull request merged**
